### ISSUE TITLE
New version of buffer

### ISSUE THREAD

**Issue by flightsurvey** [Turfjs/turf#848] opened 2017-07-19 16:44 UTC
I tried using a negative value for buffer and got an error message saying that radius had to be greater than 0. I’ve commented out the line that tests for negative radius
 
            e.exports = function(t, e, n, r) {
                if (!t) throw new Error("geojson is required");
                if (!e) throw new Error("radius is required");
                //if (e <= 0) throw new Error("radius must be greater than 0");
                if (r <= 0) throw new Error("steps must be greater than 0");
 
… a bit drastic, I know, but at least I can now draw interior buffers. Obviously this will have an impact on other functionality but as the original turf.buffer accepted a negative radius would it be possible for a more robust change to be made to support this functionality?

**Comment by DenisCarriere** [comment] 2017-07-19 16:56
Fixed in `v4.3.0` https://github.com/Turfjs/turf/pull/736
Duplicate of https://github.com/Turfjs/turf/issues/745

**Closed by DenisCarriere** 2017-07-19 16:56 UTC

**Comment by flightsurvey** [comment] 2017-07-19 17:09
Thank you.

**Comment by DenisCarriere** [comment] 2017-07-19 17:11
Feel free to open the issue again if it doesn't work, but I've just confirmed this and it is working on the latest release.

**Comment by flightsurvey** [comment] 2017-07-19 17:14
Works fine. Many thanks.
