### ISSUE TITLE
No type definitions for `point`, `lineString`, ...

### ISSUE THREAD

**Issue by sancarn** [Turfjs/turf#2397] opened 2023-02-14 17:52 UTC
Not sure if this is intentional, but it appears there is no type definitions for `turf.point()` and `turf.lineString()`. Have these functions been replaced or moved perhaps?

**Comment by JamesLMilner** [comment] 2023-02-26 14:59
Can you give a bit more description of what you mean by `there is no type definitions for turf.point() and turf.lineString()` ? Perhaps share a code snippet and the behaviour you were expecting?

I am able to see the types for `point` and `lineString` as expected.

Code:
https://codesandbox.io/s/types-point-linestring-zvtpdu?file=/src/index.ts

Screenshot:
![point-linestring](https://user-images.githubusercontent.com/8822075/221418407-e02304ff-af5c-4e6c-a329-05ee5e043fd8.png)

**Comment by rowanwins** [comment] 2023-05-02 09:28
Closing due to no feedback and not reproducible

**Closed by rowanwins** 2023-05-02 09:28 UTC
Labels: typescript, awaiting feedback
