### ISSUE TITLE
Apply equidistance @turf/buffer to polygons

### ISSUE THREAD

**Issue by flightsurvey** [Turfjs/turf#660] opened 2017-04-11 13:11 UTC
Please see attached screen shot of a buffer created around a polygon. It appears that the north and south extents are further away than they should be.
![buffer](https://cloud.githubusercontent.com/assets/13222323/24910782/c2d1e5b8-1ec0-11e7-9edd-4ff399934d51.png)

**Comment by DenisCarriere** [comment] 2017-04-11 13:51
Please provide a GeoJSON of the input & output.

Have you tried measuring the buffer distances using http://geojson.io?

Also there might be some distance distortions the higher/lower you are in latitudes since the buffer distance units are calculated in Degrees and not in metric/imperial units.

An example of two points up north (Resolute Bay).
![image](https://cloud.githubusercontent.com/assets/550895/24912383/f2b425a4-1e9b-11e7-9154-eb735ece1de3.png)

Ref: https://github.com/Turfjs/turf/issues/283 https://github.com/Turfjs/turf/issues/88 https://github.com/Turfjs/turf/pull/656

**Comment by flightsurvey** [comment] 2017-04-11 14:58
Thanks for getting back.

I put the following into geojson.io:
 
[http://bl.ocks.org/anonymous/raw/a8a2f66eb676b01a40676077d8ebd7fe/]

and it appears that the problem is with the other way around:

Zipped geoJSON: [map.zip](https://github.com/Turfjs/turf/files/913632/map.zip)

**Comment by DenisCarriere** [comment] 2017-04-11 15:05
**Note:** Instead of zipping, you could simply share your URL as a Gist:

https://gist.github.com/f66c382ee9ee9d8e0894b9e61f2af3d1

**Comment by flightsurvey** [comment] 2017-04-11 15:17
The zip is the geoJSON featurecollection of both polygons ...

**Comment by flightsurvey** [comment] 2017-04-11 15:22
Good tip (took me a while to absorb it).

**Comment by DenisCarriere** [comment] 2017-04-16 06:29
@flightsurvey To extend my answer, the issue is because the `radius` param is being converted from degrees to distance (miles/kilometers).

**Solution:**
Looks like we would need to apply the `@turf/buffer` operations on coordinates using the Mercator projection (then converted back to degrees WGS84), this would create an equi-distance buffer around the geometry (left, right, top & bottom should all have the same buffer distance).

## Issue - Polygon in northern latitude

- **Red:** Input Polygon
- **Blue:** Buffer with 15 miles radius
- Top & Bottom buffer distance (~15 miles)
- Left & Right buffer distance (~4 miles)
![image](https://cloud.githubusercontent.com/assets/550895/25069316/df55e782-224b-11e7-92d3-0beb5e807138.png)

**Comment by flightsurvey** [comment] 2017-04-16 12:30
Thanks for taking time to look at it

**Comment by w8r** [comment] 2017-05-02 15:57
I took this challenge before here https://github.com/w8r/moscow-rings, maybe you'll find it useful.
Basically, I extracted the equidistant projection calculation from `d3`, and adjusted it to have its center in the middle of the buffered shape. It doesn't completely remove the distortions, but at least makes sense in practical cases.

**Comment by DenisCarriere** [comment] 2017-05-02 20:44
👍 Awesome stuff! The visual map looks are pretty darn good!

Useful reference from `moscow-rings`: 
- [src/projection.js](https://github.com/w8r/moscow-rings/blob/gh-pages/src/projection.js)
- [src/geojson.js](https://github.com/w8r/moscow-rings/blob/gh-pages/src/geojson.js)

Any reason why you didn't use your [`polygon-offset`](https://github.com/w8r/polygon-offset) library vs. `jsts`?

I've briefly discussed this in other posts, however i'll go over the ideal buffer workflow:
- Reproject GeoJSON from degrees to EPSG:3857 (Web Mercator) using BBox/Center of GeoJSON (can be done with `d3.geo.azimuthalEquidistant()`)
- Apply buffer operations using `jsts` or `polygon-offset` (helpers would need a conversation table for `units` > meters).
- Unproject GeoJSON (EPGS:3857 to EPSG:4326 "WGS84")

@w8r Sounds about right? Correct me if something is off.

@mourner @morganherlocker : By no means we should support reprojections (only internally). This seems like this is the only accurate option for equi-distance buffers.  As for performance, I believe the heavy lifting is the buffer operations and not the reprojection.

**Comment by w8r** [comment] 2017-05-02 21:21
Oh, I forgot how shitty that code is)) Didn't use polygon offset, cause it was a very naive implementation before I stumbled upon martinez algorithm, and there was no proper settings to make the contour smooth, nor did it support holes in polygons.

As for the outline - why to mercator? The most important point is that you have to do the geometrical calculations in the R<sup>2</sup> space where they make sense, so abstract equidistant does the trick. This is what I do there, EPSG:3857 is only used to get the distances in meters and project back onto the leaflet map.

Your note about performance is right, offsetting is much heavier than reprojection

**Comment by DenisCarriere** [comment] 2017-05-02 22:31
👍 Thanks @w8r for the feedback, I'll have a look at it further and i'll CC you whenever I do a PR on Turf.

**Comment by DenisCarriere** [comment] 2017-05-07 02:02
This is fixed in PR https://github.com/Turfjs/turf/pull/718
Thanks @w8r & @flightsurvey for the feedback

**Closed by DenisCarriere** 2017-05-07 02:02 UTC
Labels: bug

**Comment by YanCallier** [comment] 2023-10-02 15:01
Hi, I experienced the same issue in the 6.5 version : 
![image](https://github.com/Turfjs/turf/assets/45624004/475b639f-0666-48ba-ba48-a3234b5acb38)

The circle has the same diameter used on :
const test = buffer(poly, 50, { units: 'kilometers' });

Yan
