### ISSUE TITLE
'@turf/union@^6.5.0' is not in this registry.

### ISSUE THREAD

**Issue by lgln-mw** [Turfjs/turf#2436] opened 2023-05-15 10:00 UTC
https://registry.npmjs.org/@turf%2funion returns {"error":"Not found"}

**Comment by globsecure** [comment] 2023-05-15 10:36
+1

**Comment by alenocera** [comment] 2023-05-15 12:47
Seems closed as per https://status.npmjs.org/incidents/drj38qn6qm59 shown.
I've retried a few minutes ago and seems all ok

**Comment by GregorSondermeier** [comment] 2023-05-15 13:39
Duplicate of https://github.com/Turfjs/turf/issues/2437 and seems to be already resolved :)

**Closed** 2023-05-15 13:48 UTC
