### ISSUE TITLE
Re: Issue #1547

### ISSUE THREAD

**Issue by flightsurvey** [Turfjs/turf#1569] opened 2019-01-14 23:06 UTC
Please provide the following when reporting an issue:

- [ ] GeoJSON data as a [gist file](https://gist.github.com/) or [geojson.io](http://geojson.io/) (filename extension must be `.geojson`).
- [ ] Snippet of source code or for complex examples use [jsfiddle](https://jsfiddle.net/).

**Comment by flightsurvey** [comment] 2019-01-14 23:07
Would someone be able to look at the issue I raised regarding the width of a buffer in [#1547](https://github.com/Turfjs/turf/issues/1569)? Cheers.

**Comment by rowanwins** [comment] 2019-01-15 21:52
Duplicate of #1547 . Reporting an issue once is sufficient, our unpaid maintainers do our best to respond to issues and clogging up the repo with more issues doesn't help.

**Closed by rowanwins** 2019-01-15 21:52 UTC

**Comment by flightsurvey** [comment] 2019-01-15 21:54
Apologies for causing any offence which was not my intention.

**Comment by rowanwins** [comment] 2019-01-15 21:57
All good :)
