### ISSUE TITLE
turf.along calculation result has deviation

### ISSUE THREAD

**Issue by newz-max** [Turfjs/turf#2402] opened 2023-02-26 08:16 UTC
Please provide the following when reporting an issue:

- [x] The version of Turf you are using, and any other relevant versions
- [x] GeoJSON data as a [gist file](https://gist.github.com/) or [geojson.io](http://geojson.io/) (filename extension must be `.geojson`)
- [x] Snippet of source code or for complex examples use [jsfiddle](https://jsfiddle.net/)

- Version 6.5.0
- [GeoJSON Snippet](https://geojson.io/#data=data:application/json,%7B%22type%22%3A%22FeatureCollection%22%2C%22features%22%3A%5B%7B%22type%22%3A%22Feature%22%2C%22properties%22%3A%7B%7D%2C%22geometry%22%3A%7B%22type%22%3A%22LineString%22%2C%22coordinates%22%3A%5B%5B109.502991%2C29.68718%5D%2C%5B108.837829%2C32.969237%5D%2C%5B113.567871%2C37.200787%5D%2C%5B120.567871%2C37.200787%5D%2C%5B130.567871%2C39.200787%5D%5D%7D%7D%2C%7B%22type%22%3A%22Feature%22%2C%22properties%22%3A%7B%7D%2C%22geometry%22%3A%7B%22type%22%3A%22Point%22%2C%22coordinates%22%3A%5B109.17620971312907%2C31.32863707648593%5D%7D%7D%5D%7D&map=2/0/20)
- [Code Snippet](https://jsfiddle.net/na3uojy1/12/)

**Comment by JamesLMilner** [comment] 2023-02-26 10:52
Hey @newz-max, please can you provide some context on your issue? Like a written description of what you tried and what you expected to happen?

**Comment by newz-max** [comment] 2023-02-27 01:02
I hope turf.along calculation point result always on my turf.lineString return result, but it can't, i have demo website in my issue

**Comment by smallsaucepan** [comment] 2023-12-20 23:36
Going to close this as a likely duplicate of #1362. If there's any example data or further information you can add @newz-max please attach it to that issue.

**Closed by smallsaucepan** 2023-12-20 23:36 UTC
Labels: awaiting feedback, @turf/along
