### ISSUE TITLE
Clarify in convertLength documentation usage of degree and radian units

### ISSUE THREAD

**Issue by stebogit** [Turfjs/turf#2203] opened 2021-09-15 17:09 UTC
Working on a line grid module, copying from the `@turf/rectangle-grid` package, I stumbled upon this inconsistency. Is it possible `convertLength` is off or am I missing something obvious here?

```js
const nw = turf.point([-120.20778894424438, 47.40590873190948]);
const ne = turf.destination(nw, 1, 90, { units: 'kilometers' });
const sw = turf.destination(nw, 1, 180, { units: 'kilometers' });
const se = turf.point([ne.geometry.coordinates[0], sw.geometry.coordinates[1]]);

const box = turf.bboxPolygon(turf.bbox(turf.featureCollection([nw, ne, sw, se])))

const dKm = turf.distance(nw, ne, {units: 'kilometers'});
const width = Math.abs(nw.geometry.coordinates[0] - ne.geometry.coordinates[0]);
const widthKm = turf.convertLength(width, 'degrees', 'kilometers');

console.log(dKm); // 1.0000000000004476
console.log(widthKm); // 1.4792675889975462
```

![Screen Shot 2021-09-15 at 9 24 18 AM](https://user-images.githubusercontent.com/12717225/133477532-5b455d37-61e5-4d97-8811-85b239ca3fdc.png)

The earth's curvature can't justify such big difference in a 1km distance.

The way the bbox's `width` is calculated above is the same logic [used now](https://github.com/Turfjs/turf/blob/master/packages/turf-rectangle-grid/index.ts#L57-L61) ([recently updated](https://github.com/Turfjs/turf/pull/2106)) in defining the rectangle/square grid features, but that should produce an incorrect grid result. Though I'm not sure those changes have been already published since the output of the square grid seems fine.
@rowanwins any thoughts?

**Comment by tunnelpuzzle** [comment] 2021-09-18 02:12
I think the issue is subtracting the latitude won't give you the correct degree distance.

`const width = Math.abs(nw.geometry.coordinates[0] - ne.geometry.coordinates[0]); // 0.013287829229710724
const widthDistance= turf.distance(nw, ne, {units: 'degrees'}); // 0.008982708286552414`

If your starting point was at [0, 0] for example instead of [-120.0, 47.0] it would work.

**Comment by smallsaucepan** [comment] 2024-06-26 13:18
This sounds like it wasn't an issue in the end? Closing but please reopen if it was a problem with convertLength.

**Comment by twelch** [comment] 2024-06-28 23:04
@smallsaucepan looks related to the recent #2638 and possibly the changes made in #2106.  And a difference in what `turf.distance` and `turf.convertLength` produce given the same value and units.

**Comment by twelch** [comment] 2024-06-28 23:14
I wouldn't mind updating the docs if someone could explain the difference.

**Comment by smallsaucepan** [comment] 2024-06-30 04:47
This is working ok. The distance between two longitudes (`nw.geometry.coordinates[0] - ne.geometry.coordinates[0]`) varies with latitude though. So we can't just subtract them and use that as an "angle" to feed into convertLength().

I've had in mind to add a "Units" page to the website for a while. Let's leave this open to be resolved by the addition of that page - including gotchas when using degrees and radians as units.

**Comment by smallsaucepan** [comment] 2024-11-21 05:46
@twelch can we consider this covered by PR #2748, which adds a cautionary note to the Units documentation about using degrees and radians? That page would eventually be linked to from many pages, including convertLength.

**Comment by twelch** [comment] 2024-11-22 17:19
Yes, @smallsaucepan the addition of Units docs is sufficient for me to close this.

**Closed by twelch** 2024-11-22 17:19 UTC
Labels: docs
