### ISSUE TITLE
Error installing turf

### ISSUE THREAD

**Issue by adriankwiat** [Turfjs/turf#2093] opened 2021-06-09 14:59 UTC
When I try to install Turf I get an error:
![image](https://user-images.githubusercontent.com/36125672/121378644-abf6c480-c943-11eb-8f65-5a2167305b1a.png)

None of solutions I found on Internet worked for me.

**Comment by stebogit** [comment] 2021-06-09 15:01
@adriankwiat how does your `package.json` look like?

**Comment by adriankwiat** [comment] 2021-06-09 15:17
```json
{
  "main": "dist/index.js",
  "scripts": {
    "dev": "cross-env NODE_ENV=development node -r ./dev.js --inspect src/index.ts",
    "build:next": "next build",
    "build:app": "tsc --project tsconfig.server.json",
    "build": "run-p build:*",
    "lint:es": "eslint .",
    "lint:style": "stylelint \"**/*.scss\"",
    "lint": "run-s lint:*",
    "lint-fix": "run-s \"lint:* --fix\"",
    "start": "node .",
    "start:dotenv": "node -r dotenv/config .",
    "postinstall": "husky install && shx rm -rf .git/hooks && shx ln -s ../.husky .git/hooks"
  },
  "dependencies": {
    "dotenv": "^10.0.0",
    "express": "^4.17.1",
    "helmet": "^4.6.0",
    "mongodb": "^3.6.9",
    "next": "^10.2.3",
    "next-connect": "^0.10.1",
    "next-translate": "^1.0.7",
    "react": "^17.0.2",
    "react-dom": "^17.0.2"
  },
  "devDependencies": {
    "@types/express": "^4.17.12",
    "@types/mongodb": "^3.6.17",
    "@types/node": "^15.6.1",
    "@types/react": "^17.0.8",
    "@typescript-eslint/eslint-plugin": "^4.26.0",
    "@typescript-eslint/parser": "^4.26.0",
    "autoprefixer": "^10.2.6",
    "cross-env": "^7.0.3",
    "eslint": "^7.27.0",
    "eslint-plugin-jsx-a11y": "^6.4.1",
    "eslint-plugin-react": "^7.24.0",
    "eslint-plugin-react-hooks": "^4.2.0",
    "husky": "^6.0.0",
    "lint-staged": "^11.0.0",
    "npm-run-all": "^4.1.5",
    "postcss": "^8.3.0",
    "sass": "^1.34.0",
    "shx": "^0.3.3",
    "stylelint": "^13.13.1",
    "stylelint-config-recommended-scss": "^4.2.0",
    "stylelint-config-standard": "^22.0.0",
    "stylelint-scss": "^3.19.0",
    "tailwindcss": "^2.1.3",
    "ts-node": "^10.0.0",
    "typescript": "^4.3.2",
    "yaml-loader": "^0.6.0"
  }
}
```

**Comment by stebogit** [comment] 2021-06-09 15:38
@adriankwiat I'm closing this as duplicate of https://github.com/Turfjs/turf/issues/2077.
Likely you should be able to use specific modules if you directly install the topojson dependencies.

**Closed by stebogit** 2021-06-09 15:38 UTC
