### ISSUE TITLE
transformScale doesn't always create similar shapes

### ISSUE THREAD

**Issue by DingoEatingFuzz** [Turfjs/turf#895] opened 2017-08-10 03:32 UTC
Triangles become scalene and hexagons go concave.

I discovered this while working in Glitch. Here's the project link: https://glitch.com/edit/#!/nosy-flare?path=map.js:96:8

![image](https://user-images.githubusercontent.com/174740/29153333-d7b0e0a8-7d41-11e7-972b-0204ffacbf15.png)

**Comment by rowanwins** [comment] 2017-08-11 03:27
Thanks for the report @DingoEatingFuzz 

This is one for you @stebogit :)

**Comment by DenisCarriere** [comment] 2017-08-11 03:33
Very interesting... 🤔

**Comment by stebogit** [comment] 2017-08-11 08:42
@DingoEatingFuzz the issue has something to do with the `mutate` parameter, I'll dig more into it in the weekend.
For now you can create a new scaled grid:
```js
var scaledGrid = turf.featureCollection([]);
scaledGrid.features = processedGrid.features.map(f => {
  var factors = f.properties.list.map(ms => (ms - minDate) / dateDiff);
  var avgFactor = factors.reduce((sum, n) => sum + n, 0) / factors.length;
  return turf.transformScale(f, avgFactor * (maxFactor - minFactor) + minFactor);
})

map.getSource('grid').setData(scaledGrid);
```

![screen shot 2017-08-11 at 1 37 07 am](https://user-images.githubusercontent.com/12717225/29206182-a012270c-7e35-11e7-8311-7025805b6b2a.png)

**Comment by DenisCarriere** [comment] 2017-08-11 14:55
👍 @stebogit I'll look into this, I might know where the issue is on this one. Also we can add `@turf/clone` to the mix.

**Comment by DenisCarriere** [comment] 2017-08-11 15:16
Strange one... 🤔 

I've been able to get the same "expected" results as @stebogit using a slightly different approach.

```js
processedGrid.features = processedGrid.features.map(feature => {
  var factors = feature.properties.list.map(ms => (ms - minDate) / dateDiff);
  var avgFactor = factors.reduce((sum, n) => sum + n, 0) / factors.length;
  var factor = avgFactor * (maxFactor - minFactor) + minFactor;
  return turf.transformScale(feature, factor, 'centroid')
})
```

@stebogit This is the type of "strange" unexpected mutations that @morganherlocker has been advocating, hence why all of the early TurfJS modules don't have Mutate as param since it's hard to control the expected outputs.

I initially added the `mutate` param for testing purposes.

**Comment by stebogit** [comment] 2017-08-11 15:22
@DenisCarriere this is really interesting, I thought it was not possible to map an array to "itself"
```js
processedGrid.features = processedGrid.features.map(feature => {
```
I guess JS creates a temporary copy of the array then. Cool! 👍

**Comment by DenisCarriere** [comment] 2017-08-11 15:23
Yep! `map` stores a temp array, that's why it's a bit slower than doing `featureEach` or `for` loops.

**Comment by DenisCarriere** [comment] 2017-08-11 15:24
I'm still 🤔 why this issue happening... don't know why this would cause this.

**Comment by DenisCarriere** [comment] 2017-08-11 15:24
Maybe `clone` the origin point as well?

**Comment by DenisCarriere** [comment] 2017-08-11 15:40
@stebogit Ok I've been able to make a test case for it.

![image](https://user-images.githubusercontent.com/550895/29220680-da2b24c6-7e89-11e7-9c70-2c38f7b05b7b.png)

**Comment by DenisCarriere** [comment] 2017-08-11 15:50
OOOOH I got it!
Since we are mutating the Polygon geometry, the first coordinate gets mutated and whenever it gets to the end, it uses the previously mutated coordinate instead of the original coordinate.

I think I've got a fix for this.

**Closed** 2017-08-14 17:11 UTC
Labels: bug

**Comment by amirnissim** [comment] 2024-10-13 08:10
I believe there's still an issue when passing `mutate: true` : https://github.com/Turfjs/turf/issues/2725
