### ISSUE TITLE
Distance and Buffer

### ISSUE THREAD

**Issue by lurajon** [Turfjs/turf#264] opened 2015-06-23 10:40 UTC
Hi! 
Thank you for a great JavaScript library!

I have an issue where the buffer or distance does not align correctly, and I am unsure if it is the turf library or the leaflet geodesic library that causes the problem.

I want to create functionality to draw a "circle" around a point with a given distance, and also draw the distance line.

I have created two points. I buffer the main point with the distance returned by the turf.distance(p1, p2).

The problem is that the distance line and the buffer geometry only connects on the southern and northern points of the "circle" as you can see in this jsfiddle: http://jsfiddle.net/lurajon/u5Ler6na/

Best regards,

Jone
![screen shot 2015-06-23 at 12 40 00](https://cloud.githubusercontent.com/assets/1674209/8304300/05c2985e-19a5-11e5-83d9-9ca1eee66a26.png)
![screen shot 2015-06-23 at 12 40 13](https://cloud.githubusercontent.com/assets/1674209/8304299/05bfbe5e-19a5-11e5-8a12-c0e58641fd1b.png)

**Comment by ChouGary** [comment] 2015-07-02 05:59
data is  WGS84 
but map is Mercator projection ,so the Square is rectangle !
![image](https://cloud.githubusercontent.com/assets/8294943/8470681/d048e9b6-20c1-11e5-8083-94440d0e5b42.png)
https://upload.wikimedia.org/wikipedia/commons/a/a5/Mercator_projection_Square_lo-res.JPG

**Comment by morganherlocker** [comment] 2015-07-06 18:02
This issue is a duplicate of the [turf-buffer issue](https://github.com/Turfjs/turf-buffer/issues/7). Basically, this is a known issue that is being worked on. The linked ticket has a temporary drop in copy-paste work around. PRs for geodesic polygon buffering are also welcome, as that is the blocker being worked through at the moment.

**Closed by morganherlocker** 2015-07-06 18:02 UTC

**Comment by lurajon** [comment] 2015-07-07 10:05
Thank you Morgan!

I will look into it.
