### ISSUE TITLE
turf.simplify  option does not work, always use default 1

### ISSUE THREAD

**Issue by hoogw** [Turfjs/turf#2354] opened 2022-10-21 16:54 UTC
Please provide the following when reporting an issue:

- [ ] The version of Turf you are using, and any other relevant versions.
6.5.0
- [ ] GeoJSON data as a [gist file](https://gist.github.com/) or [geojson.io](http://geojson.io/) (filename extension must be `.geojson`).
- [ ] Snippet of source code or for complex examples use [jsfiddle](https://jsfiddle.net/).

```javascript
var turfjs_simplify_options = {
    tolerance: 0.01,   // DOUGLAS-PEUCKER ALGORITHM https://cartography-playground.gitlab.io/playgrounds/douglas-peucker-algorithm/  
    highQuality: true 
    //mutate: false
};
var _geojson_clicked_simplify = turf.simplify(_geojson_clicked, turfjs_simplify_options);
```

no matter what tolerence I use, 0.01 or 1  I always get same result as 1,   
reduce to 3 vertex for 2500 vertex polygon.

option, tolerence does not hornered, during simplify process

**Comment by tmcw** [comment] 2022-11-21 19:04
Can you add a snippet or the entirety of the input polygon? This needs more information to be something we could debug and fix.

**Comment by astukanov** [comment] 2022-12-24 12:49
I am experiencing similar behavior, where the attached geojson is simplified to 2 points, start and end, regardles the provided tolerance. Also using version 6.5.0
[simplifies-to-two-points.zip](https://github.com/Turfjs/turf/files/10298592/simplifies-to-two-points.zip)

**Comment by astukanov** [comment] 2022-12-24 13:09
Further, this might be more of a feature request, but when simplifying: could it make sense to reduce the lat and lng precision a bit? I imagine it saving lots of data in certain scenarios without introducing any notable representation issues

**Comment by tmcw** [comment] 2022-12-26 15:24
That's available as turf/truncate http://turfjs.org/docs/#truncate - it's best to keep the two as separate functions, but you can just run one after the other if you want to both simplify & truncate.

To debug this we need:

- Input data
- And the code you're using

**Comment by astukanov** [comment] 2022-12-28 20:19
HI @tmcw thanks a lot for the hint, wasn't aware about the function. Makes perfect sense to me as well to keep it separate.

Hope the data in the message above is helpful for the solution to the original question. Let me know if I can help

**Comment by astukanov** [comment] 2023-04-17 20:49
I can confirm that the same behavior is happening with node.js and express backend

**Comment by elsueno** [comment] 2024-03-25 23:02
Still happens with 7.0.0-alpha.114. Are you planning to fix it?

**Comment by kaligrafy** [comment] 2024-09-20 15:27
Same here, tolerance has absolutely no effect

**Comment by smallsaucepan** [comment] 2024-10-12 04:19
@kaligrafy @elsueno @astukanov @hoogw Found the below comment on a similar issue in the simplify-js repo (which Turf uses):

> [This is because your tolerance is too high. Try something like 0.00001](https://github.com/mourner/simplify-js/issues/37#issuecomment-513812054)

Took @astukanov's example and ran it with a tolerance of 0.001 and got the resulting red line:

![Screenshot 2024-10-12 at 2 45 59 PM](https://github.com/user-attachments/assets/2efb6191-41f3-4bdb-8eb1-5b15c90cb446)

0.00002 gives the below. I had to zoom right in to see any deviation:

![Screenshot 2024-10-12 at 3 16 48 PM](https://github.com/user-attachments/assets/e654a9c4-8468-4a04-8a42-d15dedf66329)

Suspect making the tolerance value smaller will greatly improve the situation. Not sure why 0.00002 didn't work though.

**Comment by smallsaucepan** [comment] 2024-12-05 09:17
Closing as this seems to be an issue with the tolerance value passed.

**Closed by smallsaucepan** 2024-12-05 09:17 UTC
Labels: @turf/simplify
