### ISSUE TITLE
Turf-intersect does not work with lines and points after merge pull request https://github.com/Turfjs/turf/pull/1011

### ISSUE THREAD

**Issue by Knight219** [Turfjs/turf#1132] opened 2017-11-27 10:03 UTC
Fix for https://github.com/Turfjs/turf/issues/463 broke work with lines and points. 
Error in code **cleanCoords(truncate(geom2, {precision: 4})).coordinates[0].length < 4**
This condition only valid for polygons.
- For line **coordinates** is one dimensional array so **coordinates[0]** is the line's first point and length can't be more then 4.
- For point **coordinates** is not an array so **coordinates[0]** returns undefined.
Hope that description is clear even without examples.

**Comment by DenisCarriere** [comment] 2017-11-27 10:26
👍 Great description of the issue, @Knight219 could you please send a PR with an appropriate fix.

**Comment by Knight219** [comment] 2017-11-27 11:15
I'm not sure about right fix. Should lines and points skip that condition?

**Comment by DenisCarriere** [comment] 2017-11-27 19:02
No clue... however the first step would be to make test cases with the features that fail and then we can assess what to modify in the library.

@Knight219 Could you send a PR by adding a GeoJSON FeatureCollection of two objects to the `test/in` folder of `@turf/intersect`, if the tests fail (which is good) it will be easier to figure out a solution for those test cases.

**Comment by Knight219** [comment] 2017-11-28 10:54
I'm not able to push my branch with tests via https. Permission denied (

**Comment by Knight219** [comment] 2017-11-29 08:38
Any suggestions?

**Comment by DenisCarriere** [comment] 2017-11-29 08:40
Try using Git instead of https, you’ll need to push your public key to GitHub for that to work

**Comment by Knight219** [comment] 2017-11-29 08:41
I've already tried(

**Comment by Knight219** [comment] 2017-11-29 10:01
My fault. Now all works well. Link to PR https://github.com/Turfjs/turf/pull/1139

**Comment by Knight219** [comment] 2017-11-29 10:02
I've added two tests polygon with linestring and polygon with point. Polygon with point test successfull but only because **cleanCoords(truncate(geom2, {precision: 4})).coordinates[0].length** is undefined and condition is true.

**Comment by kriscarle** [comment] 2017-12-22 19:44
Hi @DenisCarriere and @Knight219 Just to add to this, MultiPolygons are also not working. When I comment out the if(cleanCoords(truncate())) small polygon checks, it works fine. I do occasionally get exceptions from JSTS but I just wrap it in a try catch.  

Happy to work on a PR fix, but I think I have a couple questions first:

1) Is intersect intended to to only support geometry type Polygon? In the README it says "takes two polygons". It doesn't seem to be a limitation of the underlying JSTS intersection, but just want to be sure. 

2) Is it okay for turf by design to throw exceptions (passed through from JSTS) or should it always return null when given bad input?

I think my preference would be for the exceptions to be thrown. I didn't discover this bug right away because null is returned both for no data and for error conditions. It wasn't until we discovered that something wasn't adding up that I figured out that my multipolygons were not being counted.

**Comment by DenisCarriere** [comment] 2017-12-22 20:23
@kriscarle I wouldn't put too much effort in fixing this issue since we are going to be dropping `jsts` in favor of `martinez` (more info here https://github.com/Turfjs/turf/issues/1195#issuecomment-353642946).

Going to close this issue for now since `@turf/intersect` won't be worked on until we drop `jsts` as a dependency.

@Knight219 Also, `@turf/intersect` does officially support other Geometry formats other than Polygon. I'd recommend using `jsts` directly if you want that support.

**Closed by DenisCarriere** 2017-12-22 20:23 UTC
Labels: bug, remove-jsts

**Comment by kriscarle** [comment] 2017-12-26 19:07
Thanks! Hadn't heard of `martinez` yet, I'll check it out.
