### ISSUE TITLE
Buffer - Observation

### ISSUE THREAD

**Issue by flightsurvey** [Turfjs/turf#849] opened 2017-07-19 19:13 UTC
This is not an issue per se, but an observation and I'm raising on behalf of a customer as I do not have an adequate enough understanding of how this module works.

There are screen captures of two scenarios below. The first shows a buffer (in orange) set at +25m and the second shows a buffer set at -25m. The first smooths out the buffer polygon (and I can just about understand why) whilst the second makes the buffer much the same shape as the object polygon. Is this in line with what everyone expects to happen?

+25 metre buffer:

![image](https://user-images.githubusercontent.com/13222323/28384741-a92cfe68-6cbd-11e7-9526-5d086b235fae.png)

-25 metre buffer:

![image](https://user-images.githubusercontent.com/13222323/28384758-bd71d7b8-6cbd-11e7-9e5e-73d9f8e3d10c.png)

It does beg the question that if I set the object polygon to be the same size as the second buffer and then apply a +25 metre buffer then what would I expect to see? A buffer with the same proportions or one that is smoothed out?

To be honest, I find both results to be acceptable from an operational point of view but I still think it's worth raising the point.

But otherwise, thank you very much for such a useful utility.

Cheers.

**Comment by DenisCarriere** [comment] 2017-07-19 20:34
Thanks for sharing 👍 

Those outcomes are expected, the smoothing edges is for normal for positive buffers.

There has been some discussion (https://github.com/Turfjs/turf/issues/639) about having other joining strategies (miter & flat).

Those screen shots look good! Good use of high resolution imagery + TurfJS.

**Comment by flightsurvey** [comment] 2017-07-19 20:53
Thank you Denis – you should see the rest of it!

 

It’s an operational planning tool for UAV (drone) operators and it’s just going into beta – https://beta.flightsurvey.com.

 

If you would like, then I’ll set up an account for you so that you can have a gander. All comments welcomed.

 

It’s great fun, really, and I am so grateful to people like you who develop these tools so that lesser developers like me can run free with their imagination.

 

All the best.

**Comment by stebogit** [comment] 2017-07-20 01:30
As just an alternative, if useful, I'd suggest the use of [`@turf/transform-scale`](https://github.com/Turfjs/turf/tree/master/packages/turf-transform-scale), which would scale the polygon keeping the original shape:

![screen shot 2017-07-19 at 6 24 56 pm](https://user-images.githubusercontent.com/12717225/28396356-b98674e6-6caf-11e7-9b01-80c34c29e7b7.png)

In this case you would need to pass the scaling factor instead of a length parameter:

```js
var scaledPoly = turf.transformScale(poly, 1.23);
```

**Comment by DenisCarriere** [comment] 2017-07-20 05:11
Oh nice! `@turf/transform-scale` is another great option for this

**Comment by rowanwins** [comment] 2017-07-25 09:45
Hey @stebogit 

A thought on this, is there any way that we could get `transformScale` to accept something other than a factor, eg it would be great to pass in a regular turf distance like kilometers...

**Comment by stebogit** [comment] 2017-07-26 16:00
👍  @rowanwins we be able to calculate the factor internally based on a `bbox` on the geojson input I guess, but let me think about it

**Comment by stebogit** [comment] 2017-07-29 07:26
@rowanwins I think we need to define how to apply a distance as `factor`. I can think about two approaches: we can apply it to the `bbox`, or add it to the distance of each point from the origin. 
The actual `factor` used for the scaling would be the ratio between `bboxes` widths or distances from origin.

Example:
```js
const scaled = turf.transformScale(polygon, 10, null, false, 'miles');
```
![triangle scale](https://user-images.githubusercontent.com/12717225/28743033-9bd451d8-73f4-11e7-958c-5da74d7a6819.png)

> The left picture is actually misleading because the two polygons could still be "centered" (if the chosen origin is the `centroid`), but I wanted to highlight where the distance would be applied.

I'm not sure if the result is what you would expect, however we can definitely add this feature.

We can add an optional `units` parameter that, if defined as a string, implies the `factor` has to be considered as a distance of that unit.

**Comment by rowanwins** [comment] 2017-07-29 09:40
Hmm yeah maybe it's not such a smart idea, might be wisest to keep that functionality in the buffer module....

**Comment by DenisCarriere** [comment] 2017-07-30 22:31
@stebogit Can't we just expand the `origin` parameter to include the `center-of-mass` & `center`?

**Comment by rowanwins** [comment] 2017-07-30 23:29
That's alright I think I've got it sorted @DenisCarriere & @stebogit . I have a fully functional polygon buffer module with 0 dependencies (other than turf deps). I'm just adding the linestring buffer before I put in an initial pull request for your review (perhaps tonight...). Currently 5 times faster than `jsts`, gone from 3,000 ops/second to 18,000. Will support holes, inverse buffers (eg with a negative value) etc. I think I can even get it support endcap strategies!

**Comment by DenisCarriere** [comment] 2017-07-31 02:55
@rowanwins 👍 Awesome! 🎉  Looking forward to it

**Comment by stebogit** [comment] 2017-07-31 04:14
> Can't we just expand the origin parameter to include the `center-of-mass` & `center`?

@DenisCarriere the `centroid` is currently the default `origin` for scale 👍

**Comment by DenisCarriere** [comment] 2017-07-31 04:16
Agreed, but couldn't we also add `center-of-mass`? wouldn't that make the output different?

**Comment by stebogit** [comment] 2017-07-31 04:30
Sorry didn't mean to close this... 😅 

@DenisCarriere I remember we defined `centroid` as default `origin` following @morganherlocker [suggestion](https://github.com/Turfjs/turf/issues/747#issuecomment-302177165). The user can anyway pass any point as `origin`.

However, here the issue is not really the `origin`, but how you would apply a distance parameter to then be able to calculate the scaling factor.

I'd actually agree with @rowanwins here, that maybe it's not the best way of think about `@turf/transform-scale`, in terms of distance increase I mean. `@turf/buffer` is definitely the best approach in this case.

**Comment by DenisCarriere** [comment] 2017-07-31 05:21
Ooh yea! that's true... The user can just pass his own point 👍 Gotcha

**Comment by DenisCarriere** [comment] 2017-07-31 05:22
> @turf/buffer is definitely the best approach in this case.

Yes this issue topic seems more of a `buffer` operation.

**Closed** 2017-08-01 06:11 UTC
Labels: question
