### ISSUE TITLE
RBush is not a constructor

### ISSUE THREAD

**Issue by adarshmadrecha** [Turfjs/turf#2200] opened 2021-09-07 13:34 UTC
## Sample Code
https://codesandbox.io/s/turf-convex-error-h9pe5

```js
import { point, featureCollection } from "@turf/helpers";
import convex from "@turf/convex";

// data from https://turfjs.org/docs/#convex
const points = featureCollection([
  point([10.195312, 43.755225]),
  point([10.404052, 43.8424511]),
  point([10.579833, 43.659924]),
  point([10.360107, 43.516688]),
  point([10.14038, 43.588348]),
  point([10.195312, 43.755225])
]);

const hull = convex(points); // This line generates error
```
![image](https://user-images.githubusercontent.com/11911938/132353822-441397aa-c476-480d-885b-400d7805282e.png)

## Details
Turf Version: 6.5.0

Please provide the following when reporting an issue:
- [x] The version of Turf you are using, and any other relevant versions.
- [x] GeoJSON data as a [gist file](https://gist.github.com/) or [geojson.io](http://geojson.io/) (filename extension must be `.geojson`).
- [x] Snippet of source code or for complex examples use [jsfiddle](https://jsfiddle.net/).

**Comment by adarshmadrecha** [comment] 2021-09-07 13:52
It looks like this issue is related to release to fix this issue https://github.com/mapbox/concaveman/issues/18

I could get turf `convex` working by installing previous version of `concaveman` `1.1.1`

![image](https://user-images.githubusercontent.com/11911938/132356208-f9c8781e-8377-45b5-895d-0e3faebf33e8.png)

**Comment by JamesLMilner** [comment] 2021-09-07 13:56
Hey @adarshmadrecha thanks for the detailed write up on the issue. Can I confirm you're using Webpack? I am pretty certain this is a duplicate of https://github.com/Turfjs/turf/issues/2191 - I think when we release a new version it should build with the fixed version of `concaveman` (1.2.1) which will resolve this.

**Comment by adarshmadrecha** [comment] 2021-09-07 14:21
@JamesLMilner , I am using `Vite` in my Actual Application.
And, as tested in CodeSandbox, which uses parcel and not webpack, it seems the issue is not related to Webpack.

**Comment by JamesLMilner** [comment] 2021-09-07 14:37
@adarshmadrecha thanks that's useful to understand. There is some issues with Webpack and `concaveman` which has been fixed in the latest version of `concaveman` (1.2.1) but the error presented here is slightly (`rbush` rather than `tinyqueue`) different and without digging in further I can't determine the root issue. 

I was able to get it working by using `concaveman@1.2.1` and `rbush@3.0.1` (both latest versions)

**Comment by JamesLMilner** [comment] 2021-09-07 19:52
Actually, simply moving rbush to `3.0.1` resolved the issue which makes sense. Again I'm pretty confident when we do a new release that is built using the latest version of concaveman that this will be resolved.

**Comment by DingoEatingFuzz** [comment] 2021-11-09 03:41
I just ran into this too using vite (by way of SvelteKit) but according to my package-lock.json I'm already using `concaveman@1.2.1` and `rbush@3.0.1`.

What's interesting in my case is that the specific error is `RBush2 is not a constructor`:

```
index.js:27 Uncaught (in promise) TypeError: RBush2 is not a constructor
    at concaveman2 (index.js:27)
    at Module.convex (index.js:45)
    at instance (index.svelte? [sm]:14)
    at init (index.mjs:1791)
    at new Routes (index.svelte? [sm]:55)
    at createProxiedComponent (svelte-hooks.js:245)
    at new ProxyComponent (proxy.js:239)
    at new Proxy<Index> (proxy.js:339)
    at create_if_block_2 (root.svelte? [sm]:38)
    at Array.create_default_slot (root.svelte? [sm]:37)
```

Looking at the source-mapped source, everything looks fine:

```js
// index the points with an R-tree
var tree = new RBush(16);
tree.toBBox = function (a) {
    return {
        minX: a[0],
        minY: a[1],
        maxX: a[0],
        maxY: a[1]
    };
};
```

But note that this uses `RBush` and not `RBush2`. The original source looks like:

```js
// node_modules/concaveman/index.js
var require_concaveman = __commonJS({
  "node_modules/concaveman/index.js"(exports, module) {
    "use strict";
    var RBush2 = (init_rbush(), rbush_exports);
    var Queue = (init_tinyqueue(), tinyqueue_exports);
    var pointInPolygon = require_point_in_polygon();
    var orient = require_orient2d_min().orient2d;
    if (Queue.default) {
      Queue = Queue.default;
    }
    module.exports = concaveman2;
    module.exports.default = concaveman2;
    function concaveman2(points2, concavity, lengthThreshold) {
      concavity = Math.max(0, concavity === void 0 ? 2 : concavity);
      lengthThreshold = lengthThreshold || 0;
      var hull = fastConvexHull(points2);
      var tree = new RBush2(16);
      tree.toBBox = function(a2) {
        return {
          minX: a2[0],
          minY: a2[1],
          maxX: a2[0],
          maxY: a2[1]
        };
      };
```

Somewhere along the line some esm shenanigans are at play. `RBush` is equivalent to `RBush2.default`.

**Comment by markcarroll** [comment] 2021-11-16 18:44
We are hitting this same issue in production when calling `turf.lineSplit`.  When will there be a new release to fix the `RBush` issue?

**Comment by enersis-pst** [comment] 2021-11-17 08:02
For us by using `booleanIntersects`

**Comment by JamesLMilner** [comment] 2021-11-19 19:05
Okay so I think I have some ideas about what might be wrong here. At the moment the `yarn.lock` file implies that `concaveman` is pinned to `1.1.1`:

https://github.com/Turfjs/turf/blob/cd719cde909db79340d390de39d2c6afe3173062/yarn.lock#L2456

The `rbush` issue can probably be tied to this as the `concaveman` fix was done in `1.2.1`  https://github.com/mapbox/concaveman/issues/18

Any app or module that uses `convex` will probably hit this issue if you are using Webpack or a bundler that suffers the same bug. The solution here is to probably pin concave man to `1.2.1`.

I can see there are older versions of rbush still present in the turf module code bases too:

https://github.com/Turfjs/turf/blob/cd719cde909db79340d390de39d2c6afe3173062/yarn.lock#L6779

For example 

* collect -  https://github.com/Turfjs/turf/blob/cd86447d5e243895eaf9bcffde4daa96e7fdfe73/packages/turf-collect/package.json#L67
* unkink - https://github.com/Turfjs/turf/blob/5375941072b90d489389db22b43bfe809d5e451e/packages/turf-unkink-polygon/package.json#L63

Think it makes sense as a minimum to bump these to +3.0.0 where it where the module was moved to a ES6 module, but also maybe to use `@turf/geojson-rbush` (cc @twelch) rather than rbush directly.

Doing these things in theory should eliminate these issues and should be on the roadmap for v7.

**Comment by JamesLMilner** [comment] 2021-11-19 21:18
This turned out to be a bit of a series of dependencies problems - we can upgrade to `concaveman` 1.2.1 which fixes the issues with `Queue` I think (https://github.com/Turfjs/turf/issues/2191) however, it also uses rbush at version 3.0.1 which is an ESM module which we can't use in turf at the moment because there is no transpiliation step. I need to confur with other Turf maintainers to determine what the best course of action would be.

I think we can fix the rbush issues in `collect` and `unkink` but unfortunately we can't fix `convex` in the same way for the reason explained above.

**Comment by JamesLMilner** [comment] 2021-11-23 10:07
I think I can work out the `rbush` bundling issues with `collect` and `unkink` (and in turn turf modules that rely on them such as `lineSlice`) but fixing `convex` is complicated. We'd either need to get `concaveman` to use the ES5 version of `rbush` or to publish a compiled ES5 version. The other potential option is to maintain our own version of `concaveman` but I'd really rather avoid that if possible.

**Comment by JamesLMilner** [comment] 2021-12-05 19:07
I'm going to close this in favour of #2191 as they are the same underlying issue.

**Closed by JamesLMilner** 2021-12-05 19:07 UTC
Labels: bug, bundling

**Comment by banapy** [comment] 2022-04-01 05:27
```
alias: {
    "rbush": __dirname + "/node_modules/rbush/rbush.js"
},
```
