### ISSUE TITLE
turf.difference

### ISSUE THREAD

**Issue by davidkell** [Turfjs/turf#347] opened 2016-04-22 12:53 UTC
Type Error: turf.difference is not a function.
Error is also appearing on the turf.js docs page.

![image](https://cloud.githubusercontent.com/assets/9785139/14741922/6b837858-0891-11e6-8314-7c3727681cc5.png)

Thanks!

**Comment by tmcw** [comment] 2016-04-23 22:30
Duplicate of #291 - this will be fixed in v3.

**Closed by tmcw** 2016-04-23 22:30 UTC
