### ISSUE TITLE
https://registry.npmjs.org/@turf/triangle-grid/-/triangle-grid-6.5.0.tgz is 404'ing

### ISSUE THREAD

**Issue by colemars** [Turfjs/turf#2458] opened 2023-07-14 20:36 UTC
https://registry.npmjs.org/@turf/triangle-grid/-/triangle-grid-6.5.0.tgz

This is causing pipeline failures.

Is this an NPM problem?

other deps e.g. https://registry.npmjs.org/@turf/transform-translate/-/transform-translate-6.5.0.tgz are returning as expected

**Comment by ryanhugh** [comment] 2023-07-14 21:13
Were having the same issue

**Comment by jhartzell** [comment] 2023-07-14 21:16
+1 so are we

**Comment by ImanMahmoudinasab** [comment] 2023-07-14 21:29
It seems the issue is with npm registry servers. It is fixed now.

**Closed** 2023-07-14 23:33 UTC
