### ISSUE TITLE
Using booleanContains cannot accurately determine the inclusion result of polygons and  polygons

### ISSUE THREAD

**Issue by BZSZ** [Turfjs/turf#2529] opened 2023-11-06 06:38 UTC
Using booleanContains cannot accurately determine the inclusion result of line segments and concave convex polygons.
version: 6.5.0

```js
import { polygon, booleanContains } from '@turf/turf';

const path1 = [
    [
        121.25,
        31.355
    ],
    [
        121.327,
        31.355
    ],
    [
        121.327,
        31.319
    ],
    [
        121.25,
        31.319
    ],
    [
        121.25,
        31.355
    ]
]
const path2 = [
    [
        121.328411,
        31.389287
    ],
    [
        121.327,
        31.355
    ],
    [
        121.25,
        31.355
    ],
    [
        121.25,
        31.319
    ],
    [
        121.327,
        31.319
    ],
    [
        121.327342,
        31.297664
    ],
    [
        121.197965,
        31.297664
    ],
    [
        121.200817,
        31.387157
    ],
    [
        121.328411,
        31.389287
    ],
    [
        121.328411,
        31.389287
    ]
]

const polygon1 = turf.polygon([path1])
const polygon2 = turf.polygon([path2])
console.log(turf.booleanContains(polygon2, polygon1))
```
![image](https://github.com/Turfjs/turf/assets/38456137/d3630d12-d49e-4a7c-981a-ba4e1e1f4bab)

The final result is true, and it is obvious from the image that the blue polygon is not contained within the orange polygon.
The orange polygon only contains all the point coordinates of the blue polygon, but does not contain the polygon.
Is there any way to correctly determine the inclusion of polygons and polygons?

**Comment by twelch** [comment] 2023-11-06 17:54
Closing as duplicate of https://github.com/Turfjs/turf/issues/2441.  Any further debugging or improvement to turf functions would be very much welcomed.  Thanks.

**Closed by twelch** 2023-11-06 17:54 UTC
