### ISSUE TITLE
boolean-contains 

### ISSUE THREAD

**Issue by abc3660170** [Turfjs/turf#1201] opened 2017-12-25 13:33 UTC
```js
var turf = require('@turf/turf')
var polygon = turf.polygon([
    [
        [
            98.8769531,
            35.3173663
        ],
        [
            83.144531,
            14.349547
        ],
        [
            111.621093,
            14.8598504
        ],
        [
            98.8769531,
            35.3173663
        ]
    ]
])
var line = turf.lineString([
    [
        111.621093,
        14.8598504
    ],
    [
        98.87369155883789,
        35.31687608544746
    ]
])

var result = turf.booleanContains(polygon,line)
console.log(result)
```

look my simple demo ,why output is true ???  Obviously this triangle does not completely contain this line.

**Comment by DenisCarriere** [comment] 2017-12-26 20:26
GeoJSON display of fixtures:

- **Red** => line
- **Blue** => polygon

![image](https://user-images.githubusercontent.com/550895/34364157-0336b014-ea51-11e7-9d3c-7d202debf5da.png)

**Comment by DenisCarriere** [comment] 2017-12-26 20:37
@abc3660170 Seems like the issue is a precision error, if the LineString uses the same coordinates as the polygon then it returns false (not contained) because the `line` exactly on the edge of the `polygon`.

```js
var line = turf.lineString([
  [
    111.621093,
    14.8598504
  ],
  [
    98.8769531,
    35.3173663
  ]
])
turf.booleanContains(polygon,line) // => false
```

Closing this issue since there's no obvious issue with the module.

**Closed by DenisCarriere** 2017-12-26 20:37 UTC

**Comment by stebogit** [comment] 2017-12-26 21:50
@DenisCarriere maybe we could add to the docs of `@turf/boolean-contains` about the perimeter overlapping or not.
Hopefully when we'll have pictures for all these modules these edge cases will become clear.

**Comment by DenisCarriere** [comment] 2017-12-26 22:51
Updating the docs would definitely make it clearer to use this module.

I've added the ESRI diagram (for now) until we have our own updated diagrams.

https://github.com/Turfjs/turf/tree/master/packages/turf-boolean-contains#diagrams

![image](https://user-images.githubusercontent.com/550895/34366100-702c12ae-ea65-11e7-8880-16cb5360be01.png)
