### ISSUE TITLE
Center line of a complex polygon ?

### ISSUE THREAD

**Issue by vlasvlasvlas** [Turfjs/turf#221] opened 2015-02-13 03:17 UTC
this kind of problem / solution:
https://smathermather.wordpress.com/2012/01/17/what-is-the-center-line-of-a-complex-polygon-new-approach/

cont'd:
https://smathermather.wordpress.com/2012/01/14/what-is-the-center-line-of-a-complex-polygon-cont-again/

Would be nice to have this draw-me-the-center-line-of-complex-polygon solution..

some people use voronoi to get this

![attachment](https://cloud.githubusercontent.com/assets/4071796/6181711/e53ae104-b315-11e4-9402-7ebbcf17baa1.png)

![scale_axis_giraffe_4_small](https://cloud.githubusercontent.com/assets/4071796/6181691/9a274482-b315-11e4-9e0f-10023804941a.png)

or some postgis solutions
![screen-shot-2012-08-09-at-9-07-05-pm](https://cloud.githubusercontent.com/assets/4071796/6181692/9f6b20da-b315-11e4-9149-c148cb4db8b1.png)

well i think this could be great at turf.

**Comment by AbelVM** [comment] 2015-03-21 11:49
Due to the discrete nature of GeoJSON features, maybe it would be easier&faster to drive through the [Straight skeleton ](http://en.wikipedia.org/wiki/Straight_skeleton) road instead of the [Medial axis](http://en.wikipedia.org/wiki/Medial_axis) one

**Comment by morganherlocker** [comment] 2016-06-01 21:22
duplicate of https://github.com/Turfjs/turf/issues/154

**Closed by morganherlocker** 2016-06-01 21:22 UTC

**Comment by vlasvlasvlas** [comment] 2016-06-02 01:34
ok!
