### ISSUE TITLE
@turf/isobands - out of memory

### ISSUE THREAD

**Issue by carlos001** [Turfjs/turf#2500] opened 2023-09-26 12:11 UTC
I am using turfjs version 6.5.
Chrome Versión 116.0.5845.188 (Build oficial) (64 bits)

Isobands fails with a "out of memory" 

Attached file is the geojson with all points
[datos.txt](https://github.com/Turfjs/turf/files/12727190/datos.txt)

The fail is generated with this breaks
[-10, 0.2, 0.65, 0.7, 0.72, 0.74, 0.75, 0.77, 1]
but with this others breaks isobands are calculated fine
[-10, 0.2, 0.65, 0.7, 0.72, 0.74, 0.75, 0.78, 1]

**Comment by smallsaucepan** [comment] 2024-06-30 09:07
Reproduced the problem with the test data and 6.5.0. Tried again with 7.0.0 and both break arrays worked fine. Will consider this resolved by the switch to the third party marchingsquares library introduced since 6.5.0.

**Closed by smallsaucepan** 2024-06-30 09:07 UTC
Labels: @turf/isobands
