### ISSUE TITLE
@turf/helpers: Regression in 6.2.0 versus 6.1.4: coordinates must contain numbers

### ISSUE THREAD

**Issue by jmealo** [Turfjs/turf#2009] opened 2021-01-18 17:21 UTC
The `find-nearest-us-cities` package works fine with @turf/helpers @ 6.1.4, however, with 6.2.0 the null/number check is broken. 

The `npm test` for that module passes with 6.1.4, and fails with 6.2.0 as an easy way to reproduce the issue.

**Error:**
```
/Users/jeff/repos/find-nearest-us-cities/node_modules/@turf/helpers/dist/js/index.js:177
        throw new Error("coordinates must contain numbers");
        ^

Error: coordinates must contain numbers
    at point (/Users/jeff/repos/find-nearest-us-cities/node_modules/@turf/helpers/dist/js/index.js:177:15)
    at /Users/jeff/repos/find-nearest-us-cities/index.js:17:25
    at Array.map (<anonymous>)
    at nearestCities (/Users/jeff/repos/find-nearest-us-cities/index.js:16:90)
    at Test.<anonymous> (/Users/jeff/repos/find-nearest-us-cities/test.js:12:24)
    at Test.bound [as _cb] (/Users/jeff/repos/find-nearest-us-cities/node_modules/tape/lib/test.js:90:32)
    at Test.run (/Users/jeff/repos/find-nearest-us-cities/node_modules/tape/lib/test.js:107:31)
    at Test.bound [as run] (/Users/jeff/repos/find-nearest-us-cities/node_modules/tape/lib/test.js:90:32)
    at Test._end (/Users/jeff/repos/find-nearest-us-cities/node_modules/tape/lib/test.js:201:11)
    at Test.bound [as _end] (/Users/jeff/repos/find-nearest-us-cities/node_modules/tape/lib/test.js:90:32)
```

**Sample code:**
```
const points = require('./US.json');
const distance = require('@turf/distance').default;
const { point } = require('@turf/helpers');
const KDBush = require('kdbush');
const geokdbush = require('geokdbush');

const index = new KDBush(points, p => p[1], p => p[2], 64);

const isFloat = (n) => Number(n) === n && n % 1 !== 0;
const nearestCities = (latitude, longitude, maxDistance, maxResults =  5) => {
    if (!isFloat(latitude)) throw new Error('`latitude` has to be a Float');
    if (!isFloat(longitude)) throw new Error('`longitude` has to be a Float');

    const pointFrom = point([latitude, longitude]);
    const maxDistanceInMeters = maxDistance ? maxDistance / 1000 : maxDistance;
    return geokdbush.around(index, latitude, longitude, maxResults, maxDistanceInMeters).map(city => {
        const pointTo = point([city.lat, city.lon]);
        city.distance = Math.ceil(distance(pointFrom, pointTo, { units: 'meters' }));
        const [name, lat, lon, state] = city;
        return {name, lat, lon, state}

    }).sort(s => s.distance)
};

module.exports = nearestCities;
```

**Comment by mfedderly** [comment] 2021-01-18 19:15
This was actually done [intentionally](https://github.com/Turfjs/turf/pull/1964) because these checks existed in 5.x but not 6.x. They were removed as a side-effect of converting the package to typescript. Although typescript can prevent the invalid points from being passed in, we still have javascript-only consumers that can benefit from the check. The check removal itself could have been a documented break from 5 to 6 but as far as I could tell it was not. One of my goals for 6.2.0 is to get users on the latest version from the 5.x series with as few breaking changes as possible, so I opted to restore this check.

Can you pre-check your points before calling `point()` or alternatively catch the error and handle it?

If there is an example point that shouldn't cause an error but does I'd love to add that as a test case and fix the logic.

As an aside, your calls to `point` have an array of `[latitude, longitude]` but turf expects `[longitude, latitude]`. I'm not sure how that affects the results of your code.

**Comment by jmealo** [comment] 2021-01-18 19:35
@mfedderly: Thanks for your reply. The issue is that the error message is wrong and it thinks that no numbers are passed in for all cases (see `npm test`). I am passing in values, the tests pass with `6.1.4` and do not with `6.2.0`. I forked this from a different script which had the values passed as documented and the results were always incorrect, when I reversed them, they became correct. It didn't make sense but correct results are correct results. I'm not sure if the data is getting flip/flopped during pre-processing, but the results are correct, I'm not sure if that's to be expected or not.

**Comment by jmealo** [comment] 2021-01-18 19:40
@mfedderly: I checked, the flipped lat/lon doesn't impact distance calculations or the bug report. Thanks for pointing that out though.

**Comment by mfedderly** [comment] 2021-01-18 21:32
I checked out your repository and set a breakpoint for the exception you are seeing. It appears that you have a bug on line 17 of test.js. You are expecting city to have `.lon` and `.lat` properties, but it is actually an array with 4 entries and not an object. You seem to correctly destructure this array on line 19.

You might also want to check your use of geokdbush, since that also appears to take longitude, latitude. Conceptually it is ordered that way because it is customary to have the x coordinate before the y coordinate. Most geospatial software uses that ordering even though it is different than the ordering that humans tend to use when speaking.

I'm going to go ahead and close this as the issue is in your code.

**Closed by mfedderly** 2021-01-18 21:32 UTC
Labels: awaiting feedback

**Comment by jmealo** [comment] 2021-01-18 21:43
@mfedderly: https://github.com/Turfjs/turf/issues/1977

**Comment by jmealo** [comment] 2021-01-18 21:47
@mfedderly: I don't know what tests you're referring to?
```
const test = require('tape');
const nearestCity = require('.');

test('find-nearest-cities', function (t) {

    t.test('nearest philadelphia city', function(t) {
        t.plan(3);

        console.time("benchmark");
        const latitude = 40.02456;
        const longitude = -75.21407;
        const cities = nearestCity(latitude, longitude, undefined, 5);
        console.timeEnd("benchmark");

        t.equal(cities[0].name, 'Manayunk', 'Philadelphia (NAME) should be the first item');
        t.equal(cities[1].name, 'Wissahickon', 'Philadelphia (NAME) should be the first item');
        t.equal(cities.length, 5, 'Should find at least 5 cities for Philadelphia.');
        t.end();
    });

    t.test('nearest city for Bird in Hand', function(t) {
        t.plan(1);

        console.time("benchmark");
        const latitude = 40.03871;
        const longitude = -76.18218;
        const cities = nearestCity(latitude, longitude, undefined, 1);
        console.timeEnd("benchmark");

        const city = cities[0]

        t.equal(city.name, 'Bird in Hand', 'Bird in Hand (NAME) should be the first item');
        t.end();
    });

});
```

**Comment by jmealo** [comment] 2021-01-18 21:47
`lon` and `lat` don't appear in my tests...?

**Comment by mfedderly** [comment] 2021-01-18 22:15
Oops, good call. The line numbers are for https://github.com/jmealo/find-nearest-us-cities/blob/master/index.js not test.js.

**Comment by jmealo** [comment] 2021-01-18 22:29
@mfedderly: :facepalm: Thank you so much, I'd love to buy you a beer/pizza. `geokdbush.around` already returns an ordered set. I changed the title of the ticket to help others out in the future. My correctness tests were passing and I conflated #1977 to mean that there was an issue with the check. Sorry that I filed this upstream too hastily; I thought my parameter checking and test coverage was sufficient.
