### ISSUE TITLE
require() of ES Module node_modules/point-in-polygon-hao/dist/pointInPolygon.mjs not supported.

### ISSUE THREAD

**Issue by anatolygolushko** [Turfjs/turf#2755] opened 2024-11-28 13:13 UTC
[ERR_REQUIRE_ESM]: require() of ES Module /node_modules/point-in-polygon-hao/dist/pointInPolygon.mjs not supported.
--
Instead change the require of node_modules/point-in-polygon-hao/dist/pointInPolygon.mjs to a dynamic import() which is available in all CommonJS modules.
    at Hook._require.Module.require (/node_modules/pm2/node_modules/require-in-the-middle/index.js:101:39)
    at Object.<anonymous> (/node_modules/@turf/boolean-point-in-polygon/dist/cjs/index.cjs:2:26)
   .........
   code: 'ERR_REQUIRE_ESM'

- The version of Turf  7.1.0

**Comment by abeeb-ola** [comment] 2024-11-28 15:28
Same issue here..

**Comment by mrivasalfano** [comment] 2024-11-28 15:30
I was using turf 7.1.0 on a firebase project and now I got same error when redeploying my function

**Comment by TPorcaro** [comment] 2024-11-28 15:31
I have the same issue with the same version...

**Comment by AndriiTsok** [comment] 2024-11-28 15:42
There was a new minor release of https://github.com/rowanwins/point-in-polygon-hao/releases which probably caused the issue. Pinning it to the initial version should resolve the problem.

**Comment by yancoltro** [comment] 2024-11-28 17:13
same issue here
@AndriiTsok is correct

`"resolutions": {
    "point-in-polygon-hao": "1.0.0"
  },`
  
  works for me

**Comment by amichaud-ingtech** [comment] 2024-11-28 19:51
@yancoltro by adding the `"resolutions"` in my package didn't work for me.

I manage to fix this issue by adding `"point-in-polygon-hao": "1.1.0"` as dependency.

**Comment by Prajwal100** [comment] 2024-11-29 08:16
> @yancoltro by adding the `"resolutions"` in my package didn't work for me.
> 
> I manage to fix this issue by adding `"point-in-polygon-hao": "1.1.0"` as dependency.

Thanks.

**Comment by smallsaucepan** [comment] 2024-11-30 04:44
Underlying issue is being tracked at https://github.com/rowanwins/point-in-polygon-hao/issues/20

**Comment by kiefer-olympiasoftware** [comment] 2024-12-03 15:09
I believe this issue was fixed in 1.2.1 of `point-in-polygon-hao`. Pinning to that version using `resolutions` (yarn) has resolve the issue for me, after clearing node_modules.

**Comment by smallsaucepan** [comment] 2024-12-04 04:59
Thanks @kiefer-olympiasoftware. Think there were a few false starts with rolling out the fix, so believe it was 1.2.3 before everything was finalised.

Hopefully this should be resolved to the point workarounds like `resolutions` aren't required any more. Would someone who was affected by this via Turf mind checking and reporting back?

**Comment by kiefer-olympiasoftware** [comment] 2024-12-05 15:14
@smallsaucepan I can confirm that removing the manual resolution does work now. Thanks.

**Comment by smallsaucepan** [comment] 2024-12-06 00:44
Thanks @kiefer-olympiasoftware. Closing, though please sing out if anyone continues to experience problems.

**Closed by smallsaucepan** 2024-12-06 00:44 UTC
