### ISSUE TITLE
Bug with Turf.Buffer

### ISSUE THREAD

**Issue by snak31** [Turfjs/turf#267] opened 2015-07-13 16:19 UTC
I use Buffer function to enlarge a polygon except that the contour is not the right distance 
Example for 200Meters 
![image](https://cloud.githubusercontent.com/assets/13276528/8654611/b9f9fbf0-298b-11e5-8a02-1a56e00cf519.png)

**Comment by snak31** [comment] 2015-07-15 15:21
@morganherlocker Please Help :S

**Comment by morganherlocker** [comment] 2015-07-15 15:33
This issue is a duplicate of https://github.com/Turfjs/turf-buffer/issues/7

Long story short, this is the current expected behavior with cartesian geometry vs geodesic geography, but improvements are in development (PRs welcome; it's a big lift).

**Comment by snak31** [comment] 2015-07-15 15:35
Oh sorry for double Post and thanks you :)

**Closed** 2015-07-15 15:53 UTC
