### ISSUE TITLE
difference fall on Polygon

### ISSUE THREAD

**Issue by fbmfbm** [Turfjs/turf#748] opened 2017-05-17 11:47 UTC
Hi all,

I'm facing some trouble with turf.difference : 

operation fail allway with error : 
```
Uncaught TypeError: Cannot read property 'GeoJSONReader' of undefined
    at Object.module.exports [as difference]
```
I'm testing with plenty geoJson object types but i know that 'Polygon' is the one to use.
so i'm testing with the exemple in doc  :
```javascript
let poly1 = {
    "type": "Feature",
    "properties": {},
    "geometry": {
        "type": "Polygon",
        "coordinates": [[
            [-46.738586, -23.596711],
            [-46.738586, -23.458207],
            [-46.560058, -23.458207],
            [-46.560058, -23.596711],
            [-46.738586, -23.596711]
        ]]
    }
};
let poly2 = {
    "type": "Feature",
    "properties": {},
    "geometry": {
        "type": "Polygon",
        "coordinates": [[
            [-46.650009, -23.631314],
            [-46.650009, -23.5237],
            [-46.509246, -23.5237],
            [-46.509246, -23.631314],
            [-46.650009, -23.631314]
        ]]
    }
};

intersectionGeoJson = turf.difference(poly1, poly2);
```

And it fail with same error.... ???

It's this difference function bugged ??

Thank's for your help

**Comment by rowanwins** [comment] 2017-05-17 12:01
Hi @fbmfbm 

Can you tell us how you've brought in turf, eg are you using the built browser version or are you just using the standalone difference module via npm? A fuller code snippet of how you've incorporated turf would help.

It looks like one of the dependencies called `jsts` has not been installed or is unavailable to you for some reason.

Cheers
Rowan

**Comment by fbmfbm** [comment] 2017-05-17 12:16
Hi rowanwins,
Thank's for your answer.
I'm using the standalone module via npm as i'm using it in Vue.Js app with Webpack.

i'm just use npm install @turf/turf and require it in my bootstrap vue app like that : 

window.turf = require('turf')

I'm using other turfJs function like intersect and union that work very well...
After your message i trying to install jsts and require it globally with same commande (window.jsts = require('jsts') ) .... but same thing...

**Comment by DenisCarriere** [comment] 2017-05-17 17:27
Recently tried the `@turf/difference` & `@turf/turf` **v4.3** and everything seems to be working correctly.
```javascript
const difference = require('@turf/difference');
// or
const {difference} = require('@turf/turf');

const intersection = difference(poly1, poly2);
console.log(intersection)
```
**output for both**
```javascript
{ type: 'Feature',
  properties: {},
  geometry: { type: 'Polygon', coordinates: [ [Object] ] } }
```

Going to close this issue since this looks like a Webpack/Vue.js bundling issue and error can't be replicated.

> Might not be related, but we should make sure all `jsts` dependencies are at the same version.

- [`@turf/buffer` **jsts v1.3.0**](https://github.com/Turfjs/turf/blob/master/packages/turf-buffer/package.json)
- [`@turf/difference` **jsts v1.4.0**](https://github.com/Turfjs/turf/blob/master/packages/turf-difference/package.json)

**Closed by DenisCarriere** 2017-05-17 17:27 UTC

**Comment by rowanwins** [comment] 2017-05-17 23:31
Hi @fbmfbm 

I've used turf with vue and webpack lots with no dramas,  a fuller code snippet might help us diagnose the issue

**Comment by DenisCarriere** [comment] 2017-05-19 06:22
@fbmfbm Don't hesitate to open the issue again once you provide more information related to your specific issue.

**Comment by fbmfbm** [comment] 2017-05-19 08:47
Ok i understand.
If i find some solution, i’ll post it in this issue.

I’m looking at source for turf.difference and turf.union but both import jsts.io.GeoJSONReader() in the same way.
That’s strange as union work well in my app, and difference not (exacltly at the same source place in my component and with basic polygon exemple for exclude bad geoJson structure case). 
I’m looking in @turf/turf import in my bootstrap vueJs and component but nothing and i trying to import @turf/difference  directly but with same result.

continu to search…

thank's







fabien@fmaison.com

Tél. : 01 55 25 88 58
17bis rue Richard Lenoir
75011 PARIS

**Comment by fbmfbm** [comment] 2017-05-19 17:00
Well, finally find the pbm :
it was an babel config mistake. 
As i use laravel cli for webpack config it doesn't compiling properlly the jsts source in 'es2005'.
I need to add my custom .babelrc fille with 

`
{
   'presets': [
      ['es2015', { 'modules': false }]
   ]
}
`

That's the way.

Thank's to point me to search on jsts.

fbm

**Comment by DenisCarriere** [comment] 2017-05-24 18:58
👍 Glad to hear it works!

One of the reasons why I dislike compiling JS, the errors can be very hard to detect if the issue is because of the compiler/transpiler.
