### ISSUE TITLE
Why does a buffered point result in a oval?

### ISSUE THREAD

**Issue by djdmbrwsk** [Turfjs/turf#110] opened 2014-05-02 01:23 UTC
I know there is probably some geographical/mathematical reason, but why does a buffered point result in a oval polygon?  Thanks!

**Comment by rowanwins** [comment] 2015-01-09 05:48
Probably on a similar issue... Running a buffer on a point seems to return a very jagged circle for me at the moment. I've tried on a small buffer (eg 1km) as well as a larger one (20km) and they both seem to generate similar jaggedness. I would've expected a smoother polygon? Any tips?
![bufferexample](https://cloud.githubusercontent.com/assets/6735870/5675923/9529ead2-981e-11e4-92c2-57e5e635130c.jpg)

On a more positive note its been really fun playing with turf, it's remarkably simple to use so thank you!
Rowan

**Comment by morganherlocker** [comment] 2015-01-09 07:16
thanks @rowanwins! Buffers are circles... but geojson only really represents polygons as lists of edges. This means that a "perfect" circle is not actually possible. This is a problem related to the [coastline paradox](http://en.wikipedia.org/wiki/Coastline_paradox). In a nutshell, a circle has an infinite number of vertices if defined as a polygon, so you have to decide on a resolution for your vertices. This is currently fixed in turf-buffer, and it is unaffected by the size of the buffer. 

Also note that Leaflet does some automatic simplification of its own, so the display may be more jagged when zoomed out, even if the data you are using for calculations is more precise.

There is a branch of turf-buffer I will be pushing out in a couple days that will give you perfectly circular point buffers, as well as an optional curve resolution. This means you can specify whatever detail you would like (memory and performance *will* be affected, but you can tinker with it).

**Comment by rowanwins** [comment] 2015-01-09 07:40
thanks @morganherlocker for the description, will await the update!

**Comment by manelclos** [comment] 2015-02-11 14:26
Got into this issue today. Easy to catch if you compare it to turf.destination:

```
	var point = map.getCenter();
	var pt1 = turf.point([point.lng, point.lat]);

	if (geoms) {
		map.removeLayer(geoms);
	}

	var minx = turf.destination(pt1, 0.200, 270, 'kilometers');
	var miny = turf.destination(pt1, 0.200, 180, 'kilometers');
	var maxx = turf.destination(pt1, 0.200, 90, 'kilometers');
	var maxy = turf.destination(pt1, 0.200, 0, 'kilometers');
	var env1 = turf.envelope(turf.featurecollection([minx, miny, maxx, maxy]));

	var buffered = turf.buffer(pt1, 0.200, 'kilometers');
	var env2 = turf.envelope(buffered);
	geoms = L.geoJson([buffered, env2, env1, pt1, minx, miny, maxx, maxy]).addTo(map);
```

**Comment by djdmbrwsk** [comment] 2015-02-11 14:34
FYI, @morganherlocker did make some awesome progress on the issue.  In [this turf-buffer branch](https://github.com/Turfjs/turf-buffer/blob/artisinal/index.js) geodesic Point and LineString buffering is working.

**Comment by manelclos** [comment] 2015-02-11 14:46
Tried the pointBuffer function and it works perfect, same result! Thanks!

**Comment by devdattaT** [comment] 2015-03-27 08:52
This is an issues that seems to be working as expected for persons with a Geospatial background, but utterly wrong to others. For example see here: http://gis.stackexchange.com/questions/139677/how-to-run-turf-js-on-desktop/139690?noredirect=1#comment203375_139690

I know that it is working correctly, and producing Geodesic buffers, which is the correct way to go about it. 

Can we edit the documentation to mention that the buffer produces Geodesic buffers, which appears like an ellipse on maps with projections such as Web Mercator?

**Comment by floledermann** [comment] 2015-05-19 09:21
Letting the user specify real-world units for the current buffer implementation is definitely a bug, as these "units" are merely statically "converted" to degrees and the buffer is then calculated using degrees - which, depending on latitude, can give vastly diverging (and wrong!) results in the current implementation, like the ellipses observed by many for the point-buffering case! As far as my understanding goes, the current Turf.js implementation does not calculate a "geodesic buffer" (which would calculate the correct shape on the ellipsoid/geoid), nor an "euclidean buffer", which would have to be calculated in the projection plane (and therefore take the map projection as an argument), but is a naïve implementation treating degrees as cartesian coordinates. Which is fine, if only it were properly documented and not taking a meaningless and misleading "unit" parameter that suggests geodesic buffering. (QGis does the same thing in their buffer function, only it (correctly) doesn't let you specify a "unit")

This is very unfortunate as creating a buffer from a point is the first thing in practically all the Turf.js tutorials, so you start out with something that is wrong **and** confusing. :(

**Comment by morganherlocker** [comment] 2015-05-19 14:46
Closing in favor of the issue on turf-buffer. **TLDR: geodesic buffers are in progress. I expect them to be in the next major turf release, but geodesic polygon buffers are complex, so your patience is appreciated.**

**Closed by morganherlocker** 2015-05-19 14:46 UTC
Labels: bug, enhancement

**Comment by bensleveritt** [comment] 2016-04-14 12:21
Hate to dredge up old issues, but has the geodesic buffer for points been merged in? I'm seeing an oval, and I wanted to check it wasn't just me.

**Comment by Antenka** [comment] 2016-06-01 17:17
Hello, I can see the updates in the standalone project here: https://github.com/Turfjs/turf-buffer/blob/artisinal/index.js
But the general packages seems like not updated:
https://github.com/Turfjs/turf/blob/master/packages/turf-buffer/index.js

Also as the client-side libruary: turf.min.js

Any plans about spreading the change around?

**Comment by tmcw** [comment] 2016-06-01 17:51
Hi Antenka,

The file you link to is in the 'artisinal' branch of turf-buffer: the 'master' branch is the one containing finished, deployed work. The other branch is not yet finished - when it is finished, it will be merged into master and the buffers generated by master will follow its approach.

**Comment by Antenka** [comment] 2016-06-01 20:01
Hi, thanks for such fast response. Any plans about when it planned to be finished/merged?

**Comment by tmcw** [comment] 2016-06-01 20:13
Unfortunately not; you can refer to the JSTS removal ticket - https://github.com/Turfjs/turf/issues/88 for the depth of this task. Many people have tried, none have succeeded in finishing the fundamental geometry algorithms we need to move past JSTS. Your help would be much appreciated if you can offer it.

**Comment by mclaeysb** [comment] 2016-06-12 18:47
Hi there! I gave it a try. See my [pull request](https://github.com/Turfjs/turf-buffer/pull/33) in turf-buffer. All comments welcome!

**Comment by jaapster** [comment] 2017-11-06 10:48
Hi, any progress on this issue? I too get the oval and if I measure the radii from the center of the oval, it is clear that this buffer is not calculated correctly. Different distance in NS direction compared to SW direction.

**Comment by marcosnc08** [comment] 2018-10-24 00:10
Hi! I'm having the same issue. Could anyone find a solution?

**Comment by cherurg** [comment] 2019-03-07 10:28
I faced the same problem and then I realised that I have `turf` package instead of `@turf/turf`.

**Comment by drio** [comment] 2019-09-18 20:05
I am running into the same issue described by @djdmbrwsk when running the following code.

I am trying to create a buffered point and then compute programmatically if other locations are within the "area" described by the buffered point. 
The issue is that the area created by the buffered point is not a circle but an oval. 

Details and code here: 

```
  function addBuffer(location, radius) {
    const stopPoint = turf.point(location);
    return turf.buffer(stopPoint, radius, {units: "miles"});
  }

  const ZOOM = 15;
  const map = L.map('mapid').setView(LOCATIONS.charleston, ZOOM);
  const radiusBufferMeters = 100;
  const LOCATIONS = {  
   charleston:                [32.7794759, -79.9340512],
   secondStateCoffee        : [32.779694, -79.937644],
   closeToSecondStateCoffee : [32.779663, -79.937027],
   colonialLake             : [32.778191, -79.941629],
  }

  L.tileLayer(MAP_URL, {
    attribution: ATTR,
    minZoom: ZOOM,
    maxZoom: ZOOM,
    boxZoom: false,
    zoomControl: false,
    dragging: false
  }).addTo(map);

  L.marker(LOCATIONS.secondStateCoffee, {opacity: 0.8}).addTo(map);
  L.marker(LOCATIONS.closeToSecondStateCoffee, {opacity: 0.6}).addTo(map);
  L.marker(LOCATIONS.colonialLake, {opacity: 0.8}).addTo(map);

  const circle = L.circle(LOCATIONS.secondStateCoffee, {radius: radiusBufferMeters});
  circle.addTo(map);

  // leafleat circle
  const tCircle = turf.circle(LOCATIONS.secondStateCoffee, radiusBufferMeters, {units: 'meters'});
  const gjLayer = L.geoJson(tCircle);
  L.polygon(tCircle.geometry.coordinates, {color: "red"}).addTo(map);
  
  // turf buffered Point
  const bufferedPoint = addBuffer(LOCATIONS.secondStateCoffee, radiusBufferMeters/1000);
  L.polygon(bufferedPoint.geometry.coordinates, {color: "green"}).addTo(map);
```

Output: 

<img width="320" alt="Screen Shot 2019-09-18 at 3 59 31 PM" src="https://user-images.githubusercontent.com/17954/65181568-55d64500-da2d-11e9-9e79-8f85b108e1f4.png">

I have also written a little [observable notebook](https://observablehq.com/@drio/exploring-leaflet) while exploring the issue. Visual aim here:

![gis](https://user-images.githubusercontent.com/17954/65181701-a057c180-da2d-11e9-931f-bff5049e3f75.gif)

**Comment by artuska** [comment] 2019-11-20 15:55
Faced the same issue — `circle` method produces ellipsis (oval) geometry. Why?

**Comment by stebogit** [comment] 2019-11-21 16:38
@drio you might want to take a look at [this](https://github.com/Turfjs/turf/issues/1793#issuecomment-556960878)

**Comment by omar-alnayme** [comment] 2020-09-28 15:34
Hi #morganherlocker is the oval buffer problem solved, I would like to thank you for the fantastic library.

**Comment by MacaScull** [comment] 2021-05-12 18:22
Sorry to bring up old issues but did anyone manage to produce geodesic buffers for polygon? Also I was just wondering what algorithm you use to produce the geodesic buffers for all shapes (points, lines, polygons)
