### ISSUE TITLE
LineOffset is not calculated correctly

### ISSUE THREAD

**Issue by FreeFrags** [Turfjs/turf#2666] opened 2024-08-05 12:15 UTC
I believe this is the same issue as https://github.com/Turfjs/turf/issues/2278 

Here is a small example of the issue, the buffer is drawn correctly 100 meters buffer but as you can see the lineoffset is incorrect. See the vertical part of the line the lineOffset is not 100 meters here..... the buffer is at 100 meters as it should be. 

[https://codesandbox.io/p/sandbox/priceless-banzai-z6f9cj](https://codesandbox.io/p/sandbox/priceless-banzai-z6f9cj)

**Comment by smallsaucepan** [comment] 2024-08-06 05:11
HI @FreeFrags. Notice you have added this example to #2278 as a comment, so will close this issue and keep tracking it there. Thanks for adding your test case 👍 

Duplicate of #2278

**Closed by smallsaucepan** 2024-08-06 05:11 UTC
