### ISSUE TITLE
pointsWithinPolygon does not give the right answer

### ISSUE THREAD

**Issue by danielengels** [Turfjs/turf#2776] opened 2024-12-17 23:09 UTC
See issue https://github.com/Turfjs/turf/issues/2443

`const turf = require("@turf/turf");

var points = turf.points([
    [
        7.1130044,
        51.1192992
    ]
  ]);
  
  var searchWithin = turf.polygon([
    [
        [
            7.1090138,
            51.1193247
        ],
        [
            7.1090144,
            51.1192983
        ],
        [
            7.1090937,
            51.1192992
        ],
        [
            7.1090929,
            51.1193251
        ],
        [
            7.1090138,
            51.1193247
        ]
    ],
  ]);
  
  var ptsWithin = turf.pointsWithinPolygon(points, searchWithin);
`

There should be no point inside.
Could it be a problem only with node.js? When I try it online with the turf sandbox it is working. No point are in ptsWithin. But when I try in on the console with node 22.11.0 the same testcase breaks.

_Originally posted by @danielengels in https://github.com/Turfjs/turf/issues/2443#issuecomment-2549795911_

**Comment by smallsaucepan** [comment] 2024-12-20 12:48
Hi @danielengels. This is a duplicate of #2443 yes? If so, can you please close this issue as a duplicate and we can keep track of your example over on #2443.

**Comment by danielengels** [comment] 2024-12-20 15:17
To be honest, i am not sure, but sure I can close it - I think it is the same. But the hao algorithmen is also faulty for some cases.
Then i used https://www.npmjs.com/package/pointinpoly and I get it working, but without turf.js.

**Closed** 2024-12-20 15:17 UTC
