### ISSUE TITLE
There are types but this result could not be resolved when respecting package.json "exports" | ts 7016

### ISSUE THREAD

**Issue by a7md0** [Turfjs/turf#2558] opened 2023-12-21 20:52 UTC
Staring new project with latest turf & TypeScript (esbuild as bundler) is throwing this error in VSCode

```ts
import { polygon } from '@turf/turf';
```

```
Could not find a declaration file for module '@turf/turf'. 'node_modules/@turf/turf/dist/es/index.js' implicitly has an 'any' type.
  There are types at 'node_modules/@turf/turf/index.d.ts', but this result could not be resolved when respecting package.json "exports". The '@turf/turf' library may need to update its package.json or typings. ts(7016)
```

- [x] The version of Turf you are using, and any other relevant versions.
  * @turf/turf `6.5.0`
  * esbuild `0.19.9`
  * typescript `5.3.3`

tsconfig.json
```json
{
  "compilerOptions": {
    "target": "es2022",
    "strict": true,
    "preserveConstEnums": true,
    "noEmit": true,
    "sourceMap": false,
    "module": "ES2022",
    "moduleResolution": "Bundler",
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "isolatedModules": true
  }
}

```

Related: https://github.com/microsoft/TypeScript/issues/52363

**Comment by smallsaucepan** [comment] 2023-12-22 02:12
Hi @a7md0. This looks like a duplicate of #2414. The way to resolve in that case is to update to one of the Turf alpha releases e.g. 7.0.0-alpha.2

**Closed by smallsaucepan** 2023-12-22 02:12 UTC

**Comment by wmonecke** [comment] 2023-12-22 11:34
@smallsaucepan How can I use types with v7.0.0-alpha.2? I cant seem to import the type Bbox for example.

**Comment by smallsaucepan** [comment] 2023-12-22 11:55
@wmonecke there are a few problems with the exports in 6.5.0. Please take a look at #2394 and if that looks similar to what you are experiencing, we have recently overhauled our exports, which will hopefully address that issue as well. Those changes won't be available until alpha.3 though, with the plan being to release that in coming days.
