### ISSUE TITLE
Error while upgrading to Angular 6

### ISSUE THREAD

**Issue by ciukstar** [Turfjs/turf#1384] opened 2018-05-04 19:26 UTC
ERROR in ./node_modules/'@turf'/meta/index.mjs
1002:15-25 Can't import the named export 'lineString' from non EcmaScript module (only default export is available)

**Comment by rowanwins** [comment] 2018-05-05 11:03
Hi @ciukstar 

This is a duplicate of #1383 but doesn't contain as much information so I'm going to close this issue, if you could follow the other issue that would be great.

Thanks,
Rowan

**Closed by rowanwins** 2018-05-05 11:03 UTC
