### ISSUE TITLE
turf.buffer calculated incorrectly, the radius of the buffer calculated is less than the actual, and latitude may not be taken into account.

### ISSUE THREAD

**Issue by 0611163** [Turfjs/turf#1662] opened 2019-04-25 09:33 UTC
Please provide the following when reporting an issue:

turf.buffer计算的不对，计算的缓冲区的半径比实际少了，可能没有考虑到纬度。

calculated incorrectly, the radius of the buffer calculated is less than the actual, and latitude may not be taken into account.

- [ ] GeoJSON data as a [gist file](https://gist.github.com/) or [geojson.io](http://geojson.io/) (filename extension must be `.geojson`).
- [ ] Snippet of source code or for complex examples use [jsfiddle](https://jsfiddle.net/).

**Comment by rowanwins** [comment] 2019-07-02 10:50
Duplicate of #1484 , #1470 & #1547

**Closed by rowanwins** 2019-07-02 10:50 UTC
