### ISSUE TITLE
[@turf/turf] Intersect always returns null

### ISSUE THREAD

**Issue by padawanDeveloper** [Turfjs/turf#2070] opened 2021-04-08 05:21 UTC
<img width="579" alt="Screen Shot 2021-04-08 at 01 06 30" src="https://user-images.githubusercontent.com/33547548/113972288-61a07c80-9808-11eb-8c86-df74338a38d2.png">

```javascript
const poly1 = {
    type: 'Feature',
    properties: {},
    geometry: {
        type: 'Polygon',
        coordinates: [
            [
                [-37.03835344778681, -72.77586791664363],
                [-37.022606172184794, -72.77586791664363],
                [-37.022606172184794, -72.75551162660123],
                [-37.03835344778681, -72.75551162660123],
                [-37.03835344778681, -72.77586791664363]
            ]
        ]
    }
};

const poly2 = {
    type: 'Feature',
    properties: {},
    geometry: {
        type: 'Polygon',
        coordinates: [
            [
                [-37.04968884926708, -66.7482388650978],
                [-37.04990168905576, -66.75947610848424],
                [-37.03188742710995, -66.76000562559427],
                [-37.03167472559009, -66.74877103252062],
                [-37.04968884926708, -66.7482388650978]
            ]
        ]
    }
};

console.log(turf.intersect(poly1, poly2)) // return null
```

Hello!!
After updating Turf from version 5.1.6 to 6.3.0, I am facing an error when trying to find the intersection between these two polygons. I am following the documentation.

**Comment by rowanwins** [comment] 2021-07-30 12:22
Hi @padawanDeveloper 

Apologies for the slow reply.
Plotting your polygons on a map (either a webmap or QGIS) shows that they don't intersect, 
https://rowanwins.github.io/geojson-editor/?gist=c29f4ae134b5f700c4d65974ef565b83
I'm not sure how you generated your image.

Regards,
Rowan

**Comment by smallsaucepan** [comment] 2023-12-20 14:48
Been a couple of years since request for follow up, and bug couldn't be reproduced. Closing.

**Closed by smallsaucepan** 2023-12-20 14:48 UTC
Labels: awaiting feedback, @turf/intersect
